

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Header from "@/widgets/Header";
import { RedaxProvider } from "@/shared/lib/redux/provider";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Three Projects RTK",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RedaxProvider>

            <Header/>
            {children}

        </RedaxProvider>
      </body>
    </html>
  );
}
